import { Inter } from "next/font/google";
// import "./css/bootstrap.css";
import "bootstrap/dist/css/bootstrap.min.css";
import "./css/style.css";
import "./css/responsive.css";
const inter = Inter({ subsets: ["latin"] });

import Header from "@/components/Header";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  metadataBase: new URL("https://www.sibinfotech.com"),

  alternates: {
    canonical: "",
    languages: {
      "en-US": "/en-US",
      "de-DE": "/de-DE",
    },
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <PreloadResources /> */}
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
